# bluegreen-rollout-guestbook-ui.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-guestbook-ui
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guestbook-ui
  strategy:
    blueGreen:
      activeService: guestbook-ui-active
      previewService: guestbook-ui-preview
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
