# # guestbook-ui-preview-service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: guestbook-ui-preview
#   namespace: default
# spec:
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: guestbook-ui-preview



# apiVersion: v1
# kind: Service
# metadata:
#   name: guestbook-ui-preview
#   namespace: default
# spec:
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: guestbook-ui
#     version: preview


# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     argocd.argoproj.io/instance: demo
#   name: guestbook-ui-preview
#   namespace: default
# spec:
#   ports:
#     - port: 80
#       targetPort: 80
#   selector:
#     app: guestbook-ui
#     version: preview

apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-preview
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: guestbook-ui
    version: preview




