# # guestbook-ui-active-service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: guestbook-ui-active
#   namespace: default
# spec:
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: guestbook-ui

# guestbook-ui-active-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-active
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
